version: "3.9"
services:
  # rabbitmq service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  # python rabbitmq publisher
  publisher:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
